# Site settings
title: MARK FLINN
subtitle: :The Legend
email: alexander.kr2004@gmail.com
description: The Devil's On The Earth
baseurl: "/DevilContinent" # the subpath of your site, e.g. /blog
url: "https://chirag-kumar.github.io/" # the base hostname & protocol for your site


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
